# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']


    admin.annonce:
        class: AppBundle\Admin\AnnonceAdmin
        arguments: [~, AppBundle\Entity\Annonce, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Annonce', label: Lister les annonces,  icon: '<i class="fa fa-home"></i>', position:right }

    admin.contact:
        class: AppBundle\Admin\ContactAdmin
        arguments: [~, AppBundle\Entity\Contact, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Contact',  label: Contact,  icon: '<i class="fa fa-envelope"></i>', position:right }

    admin.fichier:
        class: AppBundle\Admin\FichierAdmin
        arguments: [~, AppBundle\Entity\Fichier, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Fichier', show_in_dashboard: false }

    app.ajouter.annonce.form.type:
        class: AppBundle\Form\AnnonceType
        arguments: ['%type_bien%', '%type_location%']
        tags:
          - { name: form.type, alias: appbundle_annonce }
